# The name of your plugin as displayed in the Plugins Catalog web UI.
displayName: Rate Limit

# For now, `middleware` is the only type available.
type: middleware

# The import path of your plugin.
import: github.com/kav789/traefik-ratelimit

# A brief description of what your plugin is doing.
summary: Rate Limit

testData:
  keeperRateLimitKey: wbpay-ratelimits
  keeperURL: http://keeper-ext.wbpay.svc.k8s.wbpay-dev:8080
  keeperAdminPassword: Pa$sw0rd
  keeperReqTimeout: 300s
